# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dataloader": "00_cluster.ipynb",
         "BayesClusterTrainer": "00_cluster.ipynb",
         "addition": "00_core.ipynb",
         "multiply": "00_core.ipynb"}

modules = ["cluster.py",
           "core.py"]

doc_url = "https://ml-pipes.github.io/fe_utils/"

git_url = "https://github.com/ml-pipes/fe_utils/tree/master/"

def custom_doc_links(name): return None
