# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"addition": "00_core.ipynb",
         "multiply": "00_core.ipynb",
         "dataloader": "cluster.ipynb",
         "BayesClusterTrainer": "cluster.ipynb"}

modules = ["core.py",
           "cluster.py"]

doc_url = "https://ml-pipes.github.io/fe_utils/"

git_url = "https://github.com/ml-pipes/fe_utils/tree/master/"

def custom_doc_links(name): return None
