# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['addition', 'multiply']

# Cell
from typing import Union

def addition(a:Union[int, float], b:Union[int, float]) -> Union[int, float]:
    """
    A simple addition function. Add `a` to `b`.
    """

    calc = a + b

    return calc

# Cell

def multiply(a : float, b: float) -> float:
    """
    fn multiplies two values `a` and `b`
    """

    return a*b