# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['addition']

# Cell
from typing import Union

def addition(a:Union[int, float], b:Union[int, float]) -> Union[int, float]:
    """
    A simple addition function. Add `a` to `b`.
    """

    return a + b